services:
  - type: web
    name: sandbox-backend
    env: python  # ESTA es la línea correcta
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
